[
	{"id":"1","judul":"Computer Vision","penulis":"Budi","kategori":"DSAI","tahunTerbit":"12/05/2017","deskripsi":"Materi yang diajarkan meliputi pengantar computer vision, formasi citra, pengolahan citra digital, pendeteksian ciri, segmentasi, motion tracking. kalibrasi kamera, 3D vision, recognition","gambarBukuUrl":"https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png"},
	{"id":"2","judul":"Soft Computing","penulis":"Reyna","kategori":"DSAI","tahunTerbit":"24/10/2015","deskripsi":"Membahas tentang logika fuzzy, Jaringan syaraf tiruan untuk menghasilkan sistem yang memiliki toleransi terhadap ketidakteraturan (imprecision), ketidakpastian (uncertainty), dan kebenaran parsial (partial truth), ANFIS","gambarBukuUrl":"https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png"},
	{"id":"3","judul":"Educational Games","penulis":"Steven","kategori":"GD","tahunTerbit":"12/12/2012","deskripsi":"Konsep dasar perancangan game edukasi serta jenis-jenisnya, elemen game desain yang memanfaatkan aspek kognitif manusia, konsep dan penerapan gamification","gambarBukuUrl":"https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png"},
	{"id":"4","judul":"Immersive Computing","penulis":"Romeo","kategori":"GD","tahunTerbit":"04/03/2002","deskripsi":"Pengembangan aplikasi berbasis augmented reality dan virtual reality","gambarBukuUrl":"https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png"},
	{"id":"5","judul":"Advanced Computer Network","penulis":"Shrek","kategori":"NCS","tahunTerbit":"10/06/2021","deskripsi":"Rancangan & Unsur dari Jaringan, Routing Static & Routing Dinamis, konfigurasi jaringan pada Router, Traffic Jaringan, serangan dan cara pengamanan pada jaringan, router & switch","gambarBukuUrl":"https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png"},
	{"id":"6","judul":"IOT Implementation","penulis":"Claire","kategori":"NCS","tahunTerbit":"02/11/2019","deskripsi":"Desain aplikasi IoT, pengembangan aplikasi IoT dengan Bahasa pemrograman popular, evaluasi implementasi aplikasi IoT dalam perusahaan","gambarBukuUrl":"https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png"},
	{"id":"7","judul":"Software Engineering Workshop","penulis":"Theo","kategori":"IMES","tahunTerbit":"10/01/2007","deskripsi":"Metodologi pengembangan perangkat lunak, dokumentasi pengembangan perangkat lunak sesuai dengan standar","gambarBukuUrl":"https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png"},
	{"id":"8","judul":"Business Geography","penulis":"Rudeus","kategori":"IMES","tahunTerbit":"16/04/2015","deskripsi":"Konsep data spasial dan jenis-jenisnya, analisa-analisa spasial, membuat aplikasi web GIS untuk suatu sistem Riil","gambarBukuUrl":"https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png"},
	{"id":"9","judul":"Enterprise Software Design Pattern","penulis":"Larry","kategori":"IMES","tahunTerbit":"08/08/2019","deskripsi":"Penerapan konsep Design Pattern pada struktur kelas program berbasis Objek dan pada studi kasus tertentu","gambarBukuUrl":"https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png"},
	{"id":"10","judul":"Pemrograman Data Spasial","penulis":"Smith","kategori":"SIB","tahunTerbit":"16/12/2008","deskripsi":"Membuat aplikasi web GIS untuk suatu sistem Riil","gambarBukuUrl":"https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png"},
	{"id":"11","judul":"Assets Design","penulis":"Kana","kategori":"MM","tahunTerbit":"11/02/2000","deskripsi":"Desain aset yang sesuai untuk aplikasi multimedia tertentu","gambarBukuUrl":"https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png"},
	{"id":"12","judul":"Digital Audio","penulis":"Ai","kategori":"MM","tahunTerbit":"23/09/2014","deskripsi":"Memberi siswa kemampuan/ Skill Sound Design, secara Hybrid (analog & digital), Music Video Arrangement, Sound & Hearing, Microphone Design and Application, Digital Audio Technology, Recording Technique","gambarBukuUrl":"https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png"},
	{"id":"13","judul":"Stop Motion","penulis":"Aqua","kategori":"MM","tahunTerbit":"15/06/2020","deskripsi":"Mengkombinasikan teknik stop motion pada mainstream video untuk mendapatkan hasil video yang unik","gambarBukuUrl":"https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png"}
]